### ISSUE TITLE
when the match ends, do we auto-jump to post-match?

### ISSUE THREAD

**Issue by Jeff-Stammler** [AdrielStammler/CPR-Scouting-App#172]
do we pause a certain length of time?

- this is doable - we do this after auto (for 3 seconds) before jumping to teleop
- if we do this, should we make it a setting that we can configure?

do we always make the scouter hit "end match"?

either way, we need to disable things so they can "finish up" what they're doing, but not create more events.  Any events created (to finish up) need to be filed with a time no greater than length of match.

Thoughts?

**Comment by AdrielStammler** [comment]
The logger already automatically maxes out the logged time to auto length + tele length so the recorded time of the "finish up" events already done. I think we should not make it end automatically immediately because when testing matches multiple times, I didn't have the time to select "climb success". Also, just because it takes them extra time doesn't mean the recorded time is after the match ended, because what's taking them extra time could be selecting an item in which case the time is already correctly recorded within the time of the match.

**Comment by Jeff-Stammler** [comment]
We decided on 9/17 during our meeting to have the scouter move to the post-match screen.

**Comment by Jeff-Stammler** [comment]
Closing.
