### ISSUE TITLE
Adding an undo button to the match page

### ISSUE THREAD

**Issue by EllaNorby** [AdrielStammler/CPR-Scouting-App#224]
Being able to undo an action if the wrong action was clicked.

**Comment by Jeff-Stammler** [comment]
We discussed this at the team reveal.  The worry is that the time it takes to UNDO an action, you might have missed another 1-2 actions.  We also potentially lose the correct time stamps, etc.

I think we settled on leaving it "as-is" and taking the acceptable risk.

Thoughts?

**Comment by EllaNorby** [comment]
I think it could be helpful, at a slower competition like Block Party there would be time to undo the action, I think it would be better to have the correct data than the exact time.

**Comment by Jeff-Stammler** [comment]
It's complicated work because the wrong event is already logged.  So let's park this until we know the rules for next season and decide then.

Perhaps we cache the log events and write them all out at the end so we can more easily manipulate the logged events.

This would be done all in the logger so the app doesn't care about implementation.  The logger close() could write it out like we do the D data.
