### ISSUE TITLE
Adding a stopped moving toggle

### ISSUE THREAD

**Issue by EllaNorby** [AdrielStammler/CPR-Scouting-App#234]
Like the is defended and defense toggles

**Comment by AdrielStammler** [comment]
Should we get rid of the last event text to fit this in or just squeeze it in.

**Comment by Jeff-Stammler** [comment]
I think we change the existing toggles.  Would it work to put the toggle BELOW the text so that it's not as wide?

If so then we can easily fit another button in there.

**Comment by AdrielStammler** [comment]
You mean the switch Icon below its own Title text. I can try to see if I can do that. So, your saying, you want to leave the `textStatus` alone?

**Comment by Jeff-Stammler** [comment]
I think i want to leave textStatus alone because i want to add "Team: " along with it so we show the team we're scouting.  There were a few times at Block where i was on the match screen and there was a delay, and i nearly forgot who i was scouting.  Yes, i knew i was Red2, but it'll help.  

Yes, i mean put the toggle below/above it's own Title text.  Might need to shrink the size of the title text to fit, and that can make the buttons much smaller.  still leave a good "padding" between buttons.
