### ISSUE TITLE
Next button

### ISSUE THREAD

**Issue by AdrielStammler** [AdrielStammler/CPR-Scouting-App#266]
The next button on the match page has the text either not there or the same color as the button.

**Comment by Jeff-Stammler** [comment]
Any idea on what the scouter did prior to this?  Which match?  Was it one match only?

**Comment by Jeff-Stammler** [comment]
It happened to me once and I was flipping the switches at the time.  I think it's because we're setting the text OUTSIDE of the runonUIThread call, and if we're in the switch_toggled onlisetener, it doesn't work because that thread isn't the ui thread anymore.  (remember some things don't work).  I put these in the runonUI part and I'm hoping that fixes it.
